name: Prod Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - run: ./gradlew test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir: -p /home/runner/.ssh
          ssh-keyscan ${{ secrets.REMOTE_HOST_DEV }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/ssh_key
          chmod 400 /home/runner/.ssh/ssh_key
      - run: pip install fabric
      - run: fabric -i /home/runner/.ssh/ssh_key -H ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST_PROD }}:${{ secrets.REMOTE_PORT }} deploy
